framework:
    messenger:
        transports:
            the-consoomer:
                dsn: '%env(CONSOOMER_TRANSPORT_DSN)%'
            the-consoomer-stream:
                dsn: '%env(CONSOOMER_STREAM_TRANSPORT_DSN)%'
            basic:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            App\VO\RawMessage: the-consoomer